"""RAGnarok Explanation Engine — generates 'Why this answer?' explanations."""

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="RAGnarok Explanation Service", version="1.0.0")


class ExplainRequest(BaseModel):
    query: str
    answer: str
    chunks: list[dict]
    model_used: str = "unknown"


@app.get("/health")
async def health():
    return {"status": "healthy", "service": "explanation-service"}


@app.post("/explain")
async def explain(req: ExplainRequest):
    """Generate a human-readable explanation of how the answer was derived."""
    num_chunks = len(req.chunks)

    # Analyze source diversity
    doc_ids = set(c.get("document_id", "") for c in req.chunks)
    num_sources = len(doc_ids)

    # Analyze relevance scores
    scores = [c.get("relevance_score", 0) for c in req.chunks]
    avg_score = sum(scores) / len(scores) if scores else 0
    max_score = max(scores) if scores else 0

    # Build reasoning steps
    reasoning_steps = [
        f"Query analyzed and classified for semantic search",
        f"Searched enterprise knowledge base using BGE embedding model",
        f"Retrieved {num_chunks} relevant chunks from {num_sources} source document(s)",
    ]

    if avg_score > 0.7:
        reasoning_steps.append("High semantic similarity found between query and retrieved documents")
    elif avg_score > 0.4:
        reasoning_steps.append("Moderate semantic similarity found; answer synthesized from multiple sources")
    else:
        reasoning_steps.append("Lower relevance scores detected; answer may be partially supported")

    if num_sources > 1:
        reasoning_steps.append(f"Cross-referenced information across {num_sources} documents for consistency")

    reasoning_steps.append(f"Answer generated using {req.model_used} with grounded context")

    # Build page references
    pages = [c.get("page_number", 0) for c in req.chunks if c.get("page_number")]
    page_info = f"Referenced pages: {', '.join(str(p) for p in sorted(set(pages)))}" if pages else ""

    summary = (
        f"Found {num_chunks} relevant passage(s) from {num_sources} document(s). "
        f"Average relevance score: {avg_score:.2f}. "
        f"Answer generated by {req.model_used} using retrieved context."
    )
    if page_info:
        summary += f" {page_info}."

    return {
        "summary": summary,
        "reasoning_steps": reasoning_steps,
        "sources_analyzed": num_sources,
        "chunks_used": num_chunks,
        "avg_relevance": round(avg_score, 4),
        "model_used": req.model_used,
    }
